baseURL = "http://beardsengaming.com/"
languageCode = "en-us"
title = "Beardsen Gaming"
theme = "ananke"
resourceDir = "../resources"

DefaultContentLanguage = "en"
#SectionPagesMenu = "main"
Paginate = 9
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Beardsen Gaming"
    weight = 1
    contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "/images/beard_logo_round.png"
  site_logo = "/images/beard_logo_round.png"
  description = "Home of Beards and D&D"
  facebook = ""
  twitter = "https://twitter.com/beardsengaming"
  instagram = ""
  youtube = "https://www.youtube.com/channel/UCTSO4xg2aIkKwILGBKOn37Q"
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-red"
  featured_image = "/images/banner.jpg"
  recent_posts_number = 3
  custom_css = ["custom.css"]
  body_classes = "modesto bg-near-white"
  #post_content_classes = "avenir bg-near-white"

[menu]
  [[menu.main]]
    name = "Home"
    weight = 1
    identifier = "home"
    url = "/"

  [[menu.main]]
    name = "Posts"
    weight = 2
    identifier = "posts"
    url = "/post/"

  [[menu.main]]
    name = "About Us"
    weight = 3
    identifier = "about"
    url = "/about/"